# SPDX-License-Identifier: Apache-2.0
#

# Base compose files for:

# ca3.example.com
# peer4.org3.example.com
# peer5.org3.example.com

version: '2'  # v3 does not support 'extends' yet

networks:
  features_default:

services:
  ca3.example.com:
    image: hyperledger/fabric-ca:1.4.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca3.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4239aa0dcd76daeeb8ba0cda701851d14504d31aad1b2ddddbac6a57365e497c_sk
    ports:
      - "8054:7054"
    command: bash -c "fabric-ca-server start -b admin:adminpw -u http://Admin@org3:org3password@ca.example.com:7054 --cfg.affiliations.allowremove --cfg.identities.allowremove -d"
    volumes:
      - ./ca3/fabric-ca-server:/etc/hyperledger/fabric-ca-server/
    container_name: ca3.example.com
    networks:
      - features_default

  peer4.org3.example.com:
    extends:
      file: peer-base.yaml
      service: peer-base
    container_name: peer4.org3.example.com
    hostname: peer4.org3.example.com
    environment:
      - CORE_PEER_ID=peer4.org3
      - CORE_PEER_ADDRESS=peer4.org3.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer4.org3.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.org3.example.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
      - ./e2e_cli/crypto-config/peerOrganizations/org3/peers/peer4.org3/msp:/etc/hyperledger/fabric/msp
      - ./e2e_cli/crypto-config/peerOrganizations/org3/peers/peer4.org3/tls:/etc/hyperledger/fabric/tls
      - ./e2e_cli/crypto-config/peerOrganizations/org3/users:/etc/hyperledger/fabric/users
      - ./scripts_ca:/home/scripts_ca/
      - ./ca-client/peer4.org3.example.com:/.fabric-ca-client/
    ports:
      - 11051:7051
      - 11052:7052
      - 11053:7053
    command: peer node start
#    command: bash -c "while true; do sleep 1; done"
    networks:
      - features_default

  peer5.org3.example.com:
    extends:
      file: peer-base.yaml
      service: peer-base
    container_name: peer5.org3.example.com
    hostname: peer5.org3.example.com
    environment:
      - CORE_PEER_ID=peer5.org3
      - CORE_PEER_ADDRESS=peer5.org3.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer5.org3.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer5.org3.example.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
      - ./e2e_cli/crypto-config/peerOrganizations/org3/peers/peer5.org3/msp:/etc/hyperledger/fabric/msp
      - ./e2e_cli/crypto-config/peerOrganizations/org3/peers/peer5.org3/tls:/etc/hyperledger/fabric/tls
      - ./e2e_cli/crypto-config/peerOrganizations/org3/users:/etc/hyperledger/fabric/users
      - ./scripts_ca:/home/scripts_ca/
      - ./ca-client/peer5.org3.example.com:/.fabric-ca-client/
    ports:
      - 12051:7051
      - 12052:7052
      - 12053:7053
    command: peer node start
#    command: bash -c "while true; do sleep 1; done"
    networks:
      - features_default


  admin3:
    container_name: admin3
    image: bsquarelab/fabric-tools-ca
#    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer4.org3.example.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3/peers/peer4.org3/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3/peers/peer4.org3/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3/peers/peer4.org3/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3/users/Admin@org3/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
      - /var/run/:/host/var/run/
      - ./e2e_cli/examples/chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
      - ./e2e_cli/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./scripts_ca:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts_ca/
      - ./scripts_ica:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts_ica/
      - ./e2e_cli/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./ca-client/org3:/.fabric-ca-client
    depends_on:
      - ca3.example.com
      - peer4.org3.example.com
      - peer5.org3.example.com
    networks:
      - features_default
